[context.production.environment]
  PERRON_HOST = "attractivejs.railsdesigner.com"
  PERRON_PROTOCOL = "https"

[build]
  command = "bin/rails perron:build"
  publish = "output"

  [build.environment]
    RAILS_ENV = "production"
    RUBY_VERSION = "3.4.5"
